### ISSUE TITLE
Implement GCE provider

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#1]
This should probably wait until the rest of the code has stabilized a bit, but eventually we need to make a GCE provider too, otherwise Cloud Brain isn't very useful.

**Comment by sarahhodne** [comment]
When starting to implement this, I realized that the HTTP API needs a few more parameters in order to fulfil the request:
- Public SSH key to be added to the server (potentially optional per provider?)
- The type of instance to start ("standard" or "premium" are probably good generic descriptors?)

I'll just add those as parameters to the `POST /instances` JSON payload.

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rMPrYNOj&#x2F;5-support-for-gce-provider-for-instance-creation-deletion-info-etc"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Support for GCE provider (for instance creation, deletion, info, etc)</a>

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WyMwCV8c&#x2F;3-support-requesting-a-new-instance-and-cloud-brain-handling-an-instance"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Support requesting a new instance and cloud-brain handling an instance</a>
