### ISSUE TITLE
Implement instance removal

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#12]
It's not yet possible to remove instances. This needs a new worker that removes instances, and also needs to update the refresh worker to remove instances that don't exist on the provider anymore.

**Comment by emdantrim** [comment]
is this like, post-job instance removal, or is this `vsphere-janitor` `gcloud-cleanup`-style instance removal?

**Comment by sarahhodne** [comment]
Post-job instance removal. The worker should send an API call to Cloud Brain saying, essentially, "I'm done with the instance, please delete it at your earliest convenience" and then Cloud Brain enqueues a background job to actually delete the instance on the backend, retrying until it's gone.

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5U9XozkY&#x2F;2-add-instance-removal"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add instance removal</a>

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
closing in favour of #26
