### ISSUE TITLE
Parse request ID into the context

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#13]
When calling the HTTP API a request ID should be passed in via a header (`X-Request-ID` or whatever Heroku uses), and then that should be parsed and added to the `context.Context` with `cbcontext.FromUUID`.

**Comment by emdantrim** [comment]
yup, `X-Request-ID`. https://devcenter.heroku.com/articles/http-request-id

**Comment by emdantrim** [comment]
closed in #15

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Tt8gahLj&#x2F;10-ensure-relevant-logging-is-in-place"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ensure relevant logging and exception monitoring is in place.</a>
