### ISSUE TITLE
Log each HTTP request

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#14]
We should maybe log every HTTP request in the http binary? Heroku will log them too, but whenever we run it locally it would be nice to have some logs of the path and method called and maybe the request time, together with the request ID and the response code?

**Comment by emdantrim** [comment]
https://github.com/travis-ci/cloud-brain/issues/13 first!

**Comment by emdantrim** [comment]
oops meant to close #13

**Comment by emdantrim** [comment]
Closed in #17

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Tt8gahLj&#x2F;10-ensure-relevant-logging-is-in-place"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ensure relevant logging and exception monitoring is in place.</a>
