### ISSUE TITLE
Implement Postgres database backend

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#2]
Right now the database is only implemented as an in-memory database for ease of use while testing. Once the "schema" has settled down a bit, we should switch to Postgres so we can have durable data.

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;MBt6fzCB&#x2F;6-use-postgres-as-persistant-data-store"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> use postgres as persistant data store</a>
