### ISSUE TITLE
Ensure proper logging and exception forwarding is in place.

### ISSUE THREAD

**Issue by emdantrim** [travis-ci/cloud-brain#21]

**Comment by solarce** [comment]
Please make a checklist linking to the relevant `TODO`s in the code

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Tt8gahLj&#x2F;10-ensure-relevant-logging-is-in-place"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ensure relevant logging and exception monitoring is in place.</a>
