### ISSUE TITLE
cloudbrain-create-token exits with no output

### ISSUE THREAD

**Issue by rkh** [travis-ci/cloud-brain#23]
Both when running via docker and directly, there is no output (token, error or otherwise) produced by running cloudbrain-create-token, both with and without sourcing `dev.env` first. The exit code is 0.

@emdantrim failed to reproduce this on her machine.

**Comment by emdantrim** [comment]
This is due to `urfave/cli` v2, which changes the behavior when you return a `fmt.Errorf` from v1. I was planning on discussing this with @meatballhat so that we can figure out why the heck it's not working on your machine (and, potentially, all Macs?).

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Fixed in https://github.com/travis-ci/cloud-brain/commit/0a62f1a3534b9caa56adf42490401b7f3281b737
