### ISSUE TITLE
Implement Redis worker.Backend

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#3]
The only worker.Backend right now is an in-memory one, which is nice for testing, but we should implement one using Redis too for production use and to be able to start making the per-process things.

Another option is to use https://github.com/jrallison/go-workers, I haven't quite decided on which to use yet.

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JKoQuSek&#x2F;7-use-redis-for-queueing"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> use redis for queueing</a>
