### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#4]
We need some form of authentication on the API. This can be implemented as a simple `http.Handler` middleware, since authorization isn't needed.

Just a simple `Authorization: token some-long-token` seems to be fairly standard for our apps, so we should probably go with that. We should also have the ability to add multiple tokens to be valid, to make it easier to rotate the tokens (add new token, deploy token everywhere, remove old token).

**Comment by emdantrim** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9UPdxhqc&#x2F;11-support-multiple-authentication-tokens-which-can-be-added-and-removed-on-the-fly"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Support multiple authentication tokens which can be added and removed on the fly.</a>
