### ISSUE TITLE
Move authentication token storage to Postgres

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#5]
Store them in a Postgres table instead of in an environment variable

**Comment by sarahhodne** [comment]
Done in 6cfd9cb80e31f7c4e23013b4225e6236205fab66

**Comment by emdantrim** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9UPdxhqc&#x2F;11-support-multiple-authentication-tokens-which-can-be-added-and-removed-on-the-fly"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Support multiple authentication tokens which can be added and removed on the fly.</a>
