### ISSUE TITLE
Add a unique ID to the background.Job struct

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#6]
The Redis worker implementation stores jobs in a (sorted) set when scheduling jobs for the future, which is what we use to re-do a job with a backoff. Since it's stored in a set, we should add a unique ID to the struct to prevent two identical jobs to become conflated into one. While I don't think two identical jobs should happen now or in the near future, it might be a cause for confusion if we do get to that point.

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YjNXjycr&#x2F;8-be-able-to-handle-instance-creation-and-deletion-through-async-background-threads"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> be able to handle instance creation and deletion through _async background threads_</a>
