### ISSUE TITLE
Allow for multiple providers in a single process

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/cloud-brain#8]
Since we've split into multiple projects, we should allow configuring multiple providers. To make this easier I'm gonna put that configuration in the database instead of trying to get it into environment variables.

**Comment by solarce** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cjbAOx7Z&#x2F;9-be-able-to-run-separate-background-threads-for-different-cloud-providers-and-be-able-to-run-multiple-background-threads-for-the-"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> be able to run separate background threads for different cloud providers _and_ be able to run multiple background threads for the same cloud provider, with different authentication credentials</a>
